repos:
-   hooks:
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    -   id: mixed-line-ending
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
-   hooks:
    -   id: poetry-check
    -   args:
        - --no-update
        id: poetry-lock
    repo: https://github.com/python-poetry/poetry
    rev: 1.6.1
-   hooks:
    -   id: absolufy-imports
    repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
-   hooks:
    -   args:
        - --fix
        id: ruff
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.292
-   hooks:
    -   id: black
    repo: https://github.com/psf/black
    rev: 23.9.1
-   hooks:
    -   id: pyright
    repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.329
