on:
  workflow_dispatch:

name: Create Debug Build

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Cache Pip
        uses: actions/cache@v2
        id: cache-pip
        with:
          path: ~\AppData\Local\pip\Cache
          key: pip-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install Pipenv
        run: python -m pip install wheel setuptools pipenv

      - name: Setup Dependencies
        run: pipenv sync
        env:
          PIPENV_VENV_IN_PROJECT: "1"

      - name: Build
        shell: pwsh
        run: ./build.ps1 -installer -debug

      - name: Zip Build
        shell: pwsh
        run: Compress-Archive -Path "./dist/MSFSModManager" -DestinationPath "./dist/MSFSModManagerPortable"

      - name: Upload Portable
        uses: actions/upload-artifact@v2
        with:
          name: Portable Executable
          path: ./dist/MSFSModManagerPortable.zip

      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: Installer
          path: ./dist/MSFSModManagerSetup.exe