on:
  workflow_dispatch:

name: Create Debug Build

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
  
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v4

      - name: Cache Poetry
        uses: actions/cache@v2
        id: cache-poetry
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-

      - name: Setup Dependencies
        run: poetry install

      - name: Build
        shell: pwsh
        run: ./build.ps1 -installer -debug

      - name: Zip Build
        shell: pwsh
        run: Compress-Archive -Path "./dist/MSFSModManager" -DestinationPath "./dist/MSFSModManagerPortable"

      - name: Upload Portable
        uses: actions/upload-artifact@v2
        with:
          name: Portable Executable
          path: ./dist/MSFSModManagerPortable.zip

      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: Installer
          path: ./dist/MSFSModManagerSetup.exe