on:
  workflow_dispatch:

name: Create Debug Build

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Cache Pip
        uses: actions/cache@v2
        id: cache-pip
        with:
          path: ~\AppData\Local\pip\Cache
          key: pip-${{ hashFiles('**/Pipfile.lock') }}

      - name: Cache Pipenv Environment
        uses: actions/cache@v2
        id: cache-pipenv
        with:
          path: .venv
          key: pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install Pipenv
        run: python -m pip install wheel setuptools pipenv

      - name: Setup Dependencies
        run: pipenv sync
        env:
          PIPENV_VENV_IN_PROJECT: "1"

      - name: Build
        run: ./build.ps1 -installer -debug

      - name: Zip Build
        run: Compress-Archive -Path "./target/MSFS Mod Manager" -DestinationPath "./target/MSFSModManagerPortable"

      - name: Upload Portable
        uses: actions/upload-artifact@v2
        with:
          name: Portable Executable
          path: ./target/MSFSModManagerPortable.zip

      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: Installer
          path: ./target/MSFS Mod ManagerSetup.exe